# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-10 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axffoodtype',
            name='childtypenames',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='axffoodtype',
            name='typeid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='axffoodtype',
            name='typename',
            field=models.CharField(max_length=64),
        ),
    ]
